POST http://localhost:3000/graphql
Content-Type: application/json


{
  "query": "mutation CreateUser($createUserInput: CreateUserInput!) { createUser(createUserInput: $createUserInput) { id email name userRole } }",
  "variables": {
    "createUserInput": {
      "email": "userr@example.com",
      "password": "seecure123",
      "name": "John Doe",
      "userRole": "SUPER_ADMIN",
      "schoolName": "Test School"
    }
  }
}