POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation CreateUser($input: CreateUserInput!) { createUser(input: $input) { id email username userRole schoolId  } }",
  "variables": {
    "input": {
      "schoolName": "Skool Acadeewee",
      "username": "admiwernusss",
      "email": "adminuwersee@example.com",
      "password": "StroerngsPass123!",
      "userRole": "SUPER_ADMIN"
    }
  }
}
