POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation Signup($signupInput: SignupInput!) { signup(signupInput: $signupInput) { accessToken user { id firstName lastName email role status school { id name subdomain status } } } }",
  "variables": {
    "signupInput": {
      "schoolName": "Green Valley High School",
      "adminFirstName": "John",
      "adminLastName": "Smith",
      "email": "admin@greenvalley.edu",
      "password": "SecurePass123!",
      "subdomain": "greenvalley"
    }
  }
}